---
- hosts: all
  gather_facts: no
  connection: network_cli
 
vars:
    #IOS FileName
    IOS: c2960c405-universalk9-mz.152-7.E2.bin
    #FTP Details
    SCP: scp://USER:PASS@X.X.X.Xc2960c405-universalk9-mz.152-7.E2.bin
    #MD5 Value
    MD5: ac54677d3afc5b165d8b7a6713fbd36f
    #boot location
    BOOT_FLASH: boot system flash:c2960c405-universalk9-mz.152-7.E2.bin
    #Login Details
    ansible_ssh_pass: SETPASS
    ansible_ssh_user: SETUSER
 
  tasks:
    - name: IOS CHECKING
      block:

      - name: GATHER FACTS
        ios_facts:
 
      - name: CHECK IF {{ IOS }} ALREADY INSTALLED
        cisco.ios.ios_command:
          commands: "show flash: | inc bin"
        register: showflash
 
      - name: Print if ios found
        when: "showflash is search(IOS)"
        meta: end_play
 
      - name: UPGRADE IOS IMAGE IF NOT COMPLIANT
        cisco.ios.ios_command:
          commands:
          - command: "copy {{ SCP }} flash:"
            prompt: '[confirm]'
            answer: ''
        register: scp
 
- hosts: all
  gather_facts: no
  connection: network_cli
 
  tasks:
    - name: VERIFY MD5
      cisco.ios.ios_command:
        commands: "verify /md5 {{ IOS }}"
      register: md5
 
    - name: SET BOOTVAR WHEN MD5 PASSES
      cisco.ios.ios_command:
        commands:
        - command: "conf t"
        - command: "{{ BOOT_FLASH }}"
        - command: "ex"
        - command: "wr"
    - debug: msg="Ready for reload"
      when: "md5 is search(MD5)"
