---
- hosts: all
  gather_facts: no
  
  tasks:
  # Show Interface Status #
    - name: show interface status
      cisco.ios.ios_command:
        commands: 
        - show interface status
      register: config
    
  # Save Output #
    - name: save output to local directory
      copy:
        content: "{{ config.stdout | replace('\\n', '\n') }}"
        dest: "/tmp/Network/{{ inventory_hostname }}_int-status.ios"
