#routers:
  hosts:
    xxxxxxxx(hostname):
      ansible_host: x.x.x.x
   vars:
      ansible_network_os: 
      ansible_user:
     
nxos:
  hosts:
   CS1:
      ansible_host: 192.168.1.181
  vars:
      ansible_network_os: cisco.nxos.nxos
      ansible_connection: ansible.netcommon.network_cli
      
#ios:
  hosts:
   xxxxxxxx(hostname):
      ansible_host: x.x.x.x
   vars:
      ansible_network_os: 
       ansible_connection: ansible.netcommon.network_cli     

#asa:
  hosts:
   xxxxxxxx(hostname):
      ansible_host: x.x.x.x
   vars:
      ansible_network_os: 
      ansible_connection: ansible.netcommon.network_cli
