---
- hosts: all
 
  tasks:
  # Gather Ansible Facts - IOS  #
    - name: Gather Ansible Facts About Access
      ios_facts:
        gather_subset:
          - all
 
# Print facts on screen #          
    - debug: 
        msg: "{{ ansible_facts }}"
 
## GLOBAL IOS FACTS SECTION ##
 
# Set Facts #
    - set_fact:
        image: "{{ ansible_facts['net_image'] }}"
        version: "{{ ansible_facts['net_version'] }}"
        serial: "{{ ansible_facts['net_serialnum'] }}"
        model: "{{ ansible_facts['net_model'] }}"
        ip_addresses: "{{ ansible_facts['net_all_ipv4_addresses'] }}"
        disk_total: "{{ ansible_facts | json_query('net_filesystems_info.bootdisk.spacetotal_kb') }}"
        disk_free: "{{ ansible_facts | json_query('net_filesystems_info.bootdisk.spacefree_kb') }}"
        mem_total: "{{ ansible_facts['net_memtotal_mb'] | default('N/A') }}"
        mem_free: "{{ ansible_facts['net_memfree_mb'] | default('N/A') }}"
 
# Create CSV file with results #
    - name: Create CSV
      copy: 
        content: | 
          {{ inventory_hostname }},{{ image }},{{ version }},{{ serial }},{{ model }},{{ disk_total }},{{ disk_free }},{{ mem_total }},{{ mem_free }}
        dest: /tmp/Network/{{ inventory_hostname }}_IOS_facts.csv       
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_IOS_facts.csv
        regexp: '\[|\]|"'
        replace: ''      
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_IOS_facts.csv
        regexp: "'"
        replace: ''
 
# Add Header Row to CSV #
    - name: Header Row
      lineinfile:
        path: /tmp/Network/{{ inventory_hostname }}_IOS_facts.csv
        insertbefore: BOF
        line: Hostname,Image,Version,Serial Number,Model,Total Disk,Free Disk,Total Memory,Free Memory
 
## Interface Facts Section ##
 
# Remove file #
    - name: Remove file (delete file)
      file:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        state: absent
 
# Create Interface CSV file with results #
    - name: Data Row
      lineinfile:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        line: "{{ item.key }},{{ item.value.description }},{{ item.value.operstatus }},{{ item.value.lineprotocol }},{% if item.value.ipv4 %} {{ item.value.ipv4 }} {% else %} NA,NA {% endif %},{{ item.value.bandwidth }},{{ item.value.duplex }},{{ item.value.macaddress }},{{ item.value.type }},{{ item.value.mediatype }},{{ item.value.mtu }}"
        create: yes
      loop: "{{ ansible_facts.net_interfaces | dict2items }}" 
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        regexp: '\[|\]|"'
        replace: ''      
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        regexp: "'"
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        regexp: "{subnet: "
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        regexp: "address: "
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        regexp: "}"
        replace: ''
 
# Add Header Row to CSV #
    - name: Header Row
      lineinfile:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.csv
        insertbefore: BOF
        line: Interface,Description,Administrative Status,Line Protocol,Subnet Mask,IP Address,Bandwidth,Duplex,MAC Address,Type,Media Type,MTU
 
# Remove file #
    - name: Remove file (delete file)
      file:
        path: /tmp/Network/{{ inventory_hostname }}_Interface_facts.md
        state: absent
        
# Neighbor Facts #
# Remove file #
    - name: Remove file (delete file)
      file:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        state: absent
 
# Create Interface CSV file with results #
    - name: Data Row
      lineinfile:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        line: "{{ item.key }},{{ item.value }}"
        create: yes
      loop: "{{ ansible_facts.net_neighbors | dict2items }}" 
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        regexp: '\[|\]|"'
        replace: ''      
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        regexp: "'"
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        regexp: "{host:"
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        regexp: "port:"
        replace: ''
 
# Format CSV #
    - name: Format CSV File Clean Up
      replace:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        regexp: "}"
        replace: ''
 
# Add Header Row to CSV #
    - name: Header Row
      lineinfile:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.csv
        insertbefore: BOF
        line: Interface,Neighbor,Port
 
# Remove file #
    - name: Remove file (delete file)
      file:
        path: /tmp/Network/{{ inventory_hostname }}_Neighbor_facts.md
        state: absent
