---
- hosts: all
  gather_facts: no


  vars_prompt:
    - name: mac_address
      prompt: mac-address (xxxx.xxxx.xxxx)? 
      private: no
  
  tasks:
  - name: Get the config
    cli_command:
      command: "{{ item }}"
    register: result


    with_items:
     - show mac address-table dynamic | i {{mac_address}}


  - debug:
      msg:
       - "{{ result.results[0].stdout_lines }}"
        
