#NTP Status Playbook

- name: NTP Status Playbook
  hosts: all
  gather_facts: no

  tasks:

   - name: Run NTP Show Commands
     cli_command:
      command: "{{ item }}"
     register: result

     with_items:
       - show clock
       - show ntp associations
       - show ntp status
     
   - debug:
       msg:
         - "{{ result.results[0].stdout_lines }}"
         - "{{ result.results[1].stdout_lines }}"
         - "{{ result.results[2].stdout_lines }}"


# Debug output can also be displayed using following lines
#  - debug:
#      msg: "{{ item.stdout_lines }}"
#    with_item
