---
- name: show ntp status ios
  hosts: all
  gather_facts: no
 
  tasks:
  - name: run ntp commands
    Cisco.ios.ios_command:
      commands: 
      - show clock
      - show ntp associations
      - show ntp status
  # Save Output #  
  - name: save output to local directory
    copy:
      content: "{{ config.stdout | replace('\\n', '\n') }}"
      dest: "/tmp/Network/{{ inventory_hostname }}_ntp-ios.ios"