---
- hosts: all
  gather_facts: no

  tasks:
  # NTP Status #
  - name: show clock
    cisco.ios.ios_command:
      commands: 
      - show clock
    register: clock

  - name: show ntp associations
    cisco.ios.ios_command:
      commands: 
        - show ntp associations 
    register: associations 

  - name: show ntp status
    cisco.ios.ios_command:
      commands: 
        - show ntp status
    register: status

  # NTP STATUS OUTPUT #
  - name: print show clock
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} clock"

  - name: print ntp assocations
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} associations"

  - name: print ntp status
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} status"
